image: jangrewe/gitlab-ci-android

stages:
- build
- deploy

cache:
  key: ${CI_PROJECT_ID}
  paths:
  - .gradle/

build:
  before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew
  only:
  - master
  stage: build
  script:
  - ./gradlew assembleDebug
  artifacts:
    paths:
    - app/build/outputs/apk/debug/*.apk

deploy:
  before_script:
    - apt-get update -qy
    - apt-get install -y lftp
    - apt-get install -y openssh-server
  stage: deploy
  script:
    lftp -e " set sftp:connect-program 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /home/user/.ssh/id_rsa_deploy';open $SFTP_HOST; user $SFTP_USER $SFTP_PASSWORD; mirror -X .* -X .*/ --reverse --verbose $SFTP_SOURCE_FOLDER $SFTP_TARGET_FOLDER; bye"
  only:
    - master

